services:
  postgresql:
    container_name: job-position-management-db
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=job_position_management