global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "job-position-management-api"

    metrics_path: /actuator/prometheus

    # Linux
    static_configs:
      - targets: ["172.17.0.1:8080"]

    # Windows and Mac
#    static_configs:
#      - targets: [ "host.docker.internal:8080" ]